/**
 * In-memory report folder store.
 * Keyed by reportId. In production this would be backed by Redis or a DB.
 *
 * Report folder shape:
 * {
 *   reportId,        — UUID generated by BFF
 *   employeeId,      — from logged-in session (hardcoded to EMP001 for prototype)
 *   reportName,      — mandatory field 1
 *   businessPurpose, — mandatory field 2
 *   policy,          — mandatory field 3
 *   reportCategory,  — mandatory field 4
 *   status,          — DRAFT | EXPENSES_LOADED | PROCESSING | REVIEW | SUBMITTED
 *   createdAt,
 *   availableExpenses,   — fetched from Layer 3
 *   processedExpenses,   — returned by Layer 2
 *   warnings             — aggregated from Layer 2 + Layer 3
 * }
 */
const store = {};

function create(reportId, fields) {
  store[reportId] = {
    reportId,
    employeeId: fields.employeeId,
    reportName: fields.reportName,
    businessPurpose: fields.businessPurpose,
    policy: fields.policy,
    reportCategory: fields.reportCategory,
    status: 'DRAFT',
    createdAt: new Date().toISOString(),
    availableExpenses: [],
    processedExpenses: [],
    warnings: []
  };
  return store[reportId];
}

function get(reportId) {
  return store[reportId] || null;
}

function update(reportId, changes) {
  if (!store[reportId]) return null;
  Object.assign(store[reportId], changes);
  return store[reportId];
}

function setStatus(reportId, status) {
  return update(reportId, { status });
}

module.exports = { create, get, update, setStatus };
