/**
 * In-memory report folder store.
 * Keyed by reportId. In production this would be backed by Redis or a DB.
 *
 * Report folder shape:
 * {
 *   reportId,        — UUID generated by BFF
 *   employeeId,      — from logged-in session (hardcoded to EMP001 for prototype)
 *   reportName,      — mandatory field 1
 *   businessPurpose, — mandatory field 2
 *   policy,          — mandatory field 3
 *   reportCategory,  — mandatory field 4
 *   status,          — DRAFT | EXPENSES_LOADED | PROCESSING | REVIEW | SUBMITTED
 *   createdAt,
 *   availableExpenses,   — fetched from Layer 3
 *   processedExpenses,   — returned by Layer 2
 *   warnings             — aggregated from Layer 2 + Layer 3
 * }
 */
const store = {};

function create(reportId, fields) {
  store[reportId] = {
    reportId,
    employeeId: fields.employeeId,
    reportName: fields.reportName,
    businessPurpose: fields.businessPurpose,
    policy: fields.policy,
    reportCategory: fields.reportCategory,
    status: 'DRAFT',
    createdAt: new Date().toISOString(),
    availableExpenses: [],
    processedExpenses: [],
    warnings: [],
    processedHashes: new Set(),   // tracks file hashes already accepted into this report
    // selectedTxnIds: null = no filter (all transactions eligible for matching)
    //                 array = user pre-selected these IDs from the landing page
    selectedTxnIds: fields.selectedTxnIds ?? null,
  };
  return store[reportId];
}

/** Check if a file hash is already registered for this report. */
function hasHash(reportId, fileHash) {
  const folder = store[reportId];
  if (!folder || !fileHash) return false;
  return folder.processedHashes.has(fileHash);
}

/** Register a file hash so subsequent uploads of the same file are rejected. */
function addHash(reportId, fileHash) {
  const folder = store[reportId];
  if (folder && fileHash) folder.processedHashes.add(fileHash);
}

/** Remove a file hash so the same file can be re-uploaded after the expense is removed. */
function removeHash(reportId, fileHash) {
  const folder = store[reportId];
  if (folder && fileHash) folder.processedHashes.delete(fileHash);
}

/** Remove a single processed expense by its expenseId (or duplicateEntryId). */
function removeExpense(reportId, expenseId) {
  const folder = store[reportId];
  if (!folder) return null;
  const expense = (folder.processedExpenses || []).find(
    e => (e.duplicateEntryId || e.expenseId) === expenseId
  );
  if (expense) {
    // Free the file hash so the same receipt can be re-uploaded
    if (expense.fileHash) removeHash(reportId, expense.fileHash);
    folder.processedExpenses = folder.processedExpenses.filter(
      e => (e.duplicateEntryId || e.expenseId) !== expenseId
    );
  }
  return expense || null;
}

function getAllProcessedHashes(reportId) {
  const folder = store[reportId];
  if (!folder) return new Set();
  return new Set(folder.processedExpenses.map(expense => expense.fileHash).filter(Boolean));
}

function get(reportId) {
  return store[reportId] || null;
}

/** Return all reports, optionally filtered by employeeId. */
function getAll(employeeId) {
  const all = Object.values(store);
  if (employeeId) return all.filter(r => r.employeeId === employeeId);
  return all;
}

function update(reportId, changes) {
  if (!store[reportId]) return null;
  Object.assign(store[reportId], changes);
  return store[reportId];
}

function setStatus(reportId, status) {
  return update(reportId, { status });
}

module.exports = { create, get, getAll, update, setStatus, hasHash, addHash, removeHash, removeExpense, getAllProcessedHashes };
